# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whiskey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01'),
            preserve_default=False,
        ),
    ]
