# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0002_auto_20160427_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtracker',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='whiskey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
