# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0003_auto_20160427_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
