# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0004_whiskey_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='comparable',
            field=models.ManyToManyField(related_name='comparables', to='whiskies.Whiskey'),
        ),
    ]
