# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0005_whiskey_comparable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsearch',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagsearch',
            name='search_string',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
