# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0007_tagsearch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
