# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0008_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
