# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0010_auto_20160511_1231'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tagtracker',
            index_together=set([('whiskey', 'tag')]),
        ),
    ]
