# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0013_auto_20160512_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsearch',
            options={'ordering': ['-created_at']},
        ),
    ]
