# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0014_auto_20160516_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskey',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
