# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0015_whiskey_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtracker',
            name='normalized_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
