# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskies', '0016_tagtracker_normalized_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskeyFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
